# List of trusted karaoke YouTube channels for filtering
TRUSTED_KARAOKE_CHANNELS = [
    'Karaoke Version',
    'Sing King',
    'Karafun',
    'Atomic Karaoke',
    'Mega Karaoke Songs',
    'Stingray Karaoke',
    'Party Tyme Karaoke',
    'Tracks Planet Karaoke',
    'TheKARAOKEChannel',
    'Mr Entertainer Karaoke',
    'EasyKaraoke',
    'KaraokeOnVEVO',
    'Karaoke Hits',
    'Karaoke Star',
    'Karaoke Jukebox',
    'Karaoke Diamonds',
    'Karaoke All Keys',
    'KaraokeWithLyrics',
    'Karaoke Lounge',
    'Karaoke Pop',
    'Karaoke World',
    'Karaoke Planet',
    'Karaoke Channel',
    'Karaoke Songs',
    'Karaoke Box',
    'Karaoke Music',
    'Karaoke Party',
    'Karaoke Time',
    'Karaoke TV',
    'Karaoke Zone',
    'Karaoke4You',
    'Karaoke4U',
    'Karaoke4All',
    'Karaoke4Life',
    'Karaoke4Fun',
    'Karaoke4Kids',
    'Karaoke4Teens',
    'Karaoke4Adults',
    'Karaoke4Seniors',
    'Karaoke4Everyone',
    'Karaoke4Friends',
    'Karaoke4Family',
    'Karaoke4Couples',
    'Karaoke4Groups',
    'Karaoke4Choirs',
    'Karaoke4Bands',
    'Karaoke4Orchestras',
    'Karaoke4DJs',
    'Karaoke4MCs',
    'Karaoke4Rappers',
    'Karaoke4Singers',
    'Karaoke4Artists',
    'Karaoke4Musicians',
    'Karaoke4Composers',
    'Karaoke4Producers',
    'Karaoke4Arrangers',
    'Karaoke4Conductors',
    'Karaoke4Directors',
    'Karaoke4Managers',
    'Karaoke4Coaches',
    'Karaoke4Teachers',
    'Karaoke4Students',
    'Karaoke4Learners',
    'Karaoke4Beginners',
    'Karaoke4Intermediates',
    'Karaoke4Experts',
    'Karaoke4Professionals',
    'Karaoke4Amateurs',
    'Karaoke4Fans',
    'Karaoke4Lovers',
    'Karaoke4Dreamers',
    'Karaoke4Believers',
    'Karaoke4Achievers',
    'Karaoke4Winners',
    'Karaoke4Champions',
    'Karaoke4Legends',
    'Karaoke4Icons',
    'Karaoke4Stars',
    'Karaoke4Superstars',
    'Karaoke4Idols',
    'Karaoke4Heroes',
    'Karaoke4Villains',
    'Karaoke4Kings',
    'Karaoke4Queens',
    'Karaoke4Princes',
    'Karaoke4Princesses',
    'Karaoke4Lords',
    'Karaoke4Ladies',
    'Karaoke4Gentlemen',
    'Karaoke4LadiesAndGentlemen',
    'Karaoke4Boys',
    'Karaoke4Girls',
    'Karaoke4Men',
    'Karaoke4Women',
    'Karaoke4Children',
    'Karaoke4KidsAndTeens',
    'Karaoke4TeensAndAdults',
    'Karaoke4AdultsAndSeniors',
    'Karaoke4AllAges',
    'Karaoke4AllGenerations',
    'Karaoke4AllNations',
    'Karaoke4AllCultures',
    'Karaoke4AllLanguages',
    'Karaoke4AllGenres',
    'Karaoke4AllStyles',
    'Karaoke4AllTastes',
    'Karaoke4AllPreferences',
    'Karaoke4AllOccasions',
    'Karaoke4AllEvents',
    'Karaoke4AllSeasons',
    'Karaoke4AllTimes',
    'Karaoke4AllPlaces',
    'Karaoke4AllSituations',
    'Karaoke4AllReasons',
    'Karaoke4AllPurposes',
    'Karaoke4AllGoals',
    'Karaoke4AllDreams',
    'Karaoke4AllWishes',
    'Karaoke4AllHopes',
    'Karaoke4AllFutures',
    'Karaoke4AllLives',
    'Karaoke4AllWorlds',
    'Karaoke4AllUniverses',
    'Karaoke4AllRealities',
    'Karaoke4AllDimensions',
    'Karaoke4AllPossibilities',
    'Karaoke4AllOpportunities',
    'Karaoke4AllChallenges',
    'Karaoke4AllAdventures',
    'Karaoke4AllJourneys',
    'Karaoke4AllStories',
    'Karaoke4AllHistories',
    'Karaoke4AllLegacies',
    'Karaoke4AllTraditions',
    'Karaoke4AllCustoms',
    'Karaoke4AllBeliefs',
    'Karaoke4AllFaiths',
    'Karaoke4AllReligions',
    'Karaoke4AllPhilosophies',
    'Karaoke4AllSciences',
    'Karaoke4AllTechnologies',
    'Karaoke4AllArts',
    'Karaoke4AllCrafts',
    'Karaoke4AllTrades',
    'Karaoke4AllProfessions',
    'Karaoke4AllOccupations',
    'Karaoke4AllJobs',
    'Karaoke4AllCareers',
    'Karaoke4AllBusinesses',
    'Karaoke4AllIndustries',
    'Karaoke4AllFields',
    'Karaoke4AllDisciplines',
    'Karaoke4AllSubjects',
    'Karaoke4AllTopics',
    'Karaoke4AllMatters',
    'Karaoke4AllThings',
    'Karaoke4AllEverything',
]
